# Generated by Django 3.2.9 on 2021-12-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecturer',
        ),
    ]
